apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: edgegateway
  name: edgegateway
spec:
  containers:
  - image: s4saif/edgegateway:v10
    name: gateway
    ports:
      - containerPort: 9000
        name: gateway
      - containerPort: 8080
        name: app
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}